### ISSUE TITLE
Messed up view in HA app on Android

### ISSUE THREAD

**Issue by Repsionu** [Samantha-uk/one#2]
**Describe the bug**
Webview on Android 10 messy

**To Reproduce**
Open ZigZag panel in companion app
**Expected behavior**

**Screenshots**
![ZigZag mobile](https://user-images.githubusercontent.com/46962963/103633088-e8b23000-4f4d-11eb-857f-79095c85b430.jpg)

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - OS: Android 10
 - Browser : HA companion app
 - Version : latest

**Additional context**
Zigs and zags are not connected to each other (see screenshot)
Best, JR
BTW it is a minor niggle as this is anyway too messy on a small screen :-)

**Comment by Samantha-uk** [comment]
Thanks for the report.
I've had other reports of a "missmatch" between elements and am working to emulate the issue here and fix it.

**Comment by Samantha-uk** [comment]
I believe that 8aa677512535b3167c83b88a81df7405adefa05f fixes this.
Can you try with the new version and let me know if it resolves your issue?

**Comment by Repsionu** [comment]
Thank You, it is fixed :-)
BTW at first I saw no improvement, even worse:
![Screenshot_20210112_201005_io homeassistant companion android](https://user-images.githubusercontent.com/46962963/104363447-dd4aa000-551d-11eb-90c9-dd92daed7dfb.jpg)
but then I remembered to wipe  app cache (sorry, hard day at office...)
![Screenshot_20210112_213023_io homeassistant companion android](https://user-images.githubusercontent.com/46962963/104363549-01a67c80-551e-11eb-9b6f-67bec61c9de1.jpg)
And voila!
Best, JR

**Comment by Samantha-uk** [comment]
Awesome!  So happy it sorted your issue.
