### ISSUE TITLE
Visualization problem on Android App

### ISSUE THREAD

**Issue by DrCoolzic** [Samantha-uk/one#5]
Each node on the zigzag graph is composed of a ‘node description’ and a ‘node circle’. On the Home assistant App the ‘descriptions’ and the ‘circles’ are disjoint (moving semi-independently). It is possible to select a 'circle' part and to move it. This result in the ‘description’ part to be moved but they stay disjointed.

![Screenshot_20210108-083909_Home Assistant](https://user-images.githubusercontent.com/6078364/104001339-c9aadc80-519f-11eb-90cf-fd7331a941b0.jpg)

Zigzag-panel 0.2.0-alpha-0.7
Home assistant server: latest version (os 5.9 / HA 2021.1.0)
Home assistant App version 3.0.2-full running on Galaxy Tab S3 (SM-T820) – Android 9

**Comment by Samantha-uk** [comment]
Thanks @DrCoolzic , another user has reported a similar issue.  I'm investigating it at the moment.  I _think_ it has to do with pixel resolution/ratios in Pixi (The circles & lines are Pixi, the icons & text are HTML)

**Comment by DrCoolzic** [comment]
Thanks. Let me know if you want me to do more tests.
May I ask quick questions? :

- For the graph construction are you using the information from the SQlite zigbee.db database?
- Do you know why the information displayed with the zha-network-card have totally different LQI values?

**Comment by DrCoolzic** [comment]
Oops did not see that there was an already open bug for that!
Do you want me to close

**Comment by Samantha-uk** [comment]
No ... it is not listed in the issues log, just a Discord message an early alpha tester reported.

**Comment by MattWestb** [comment]
@DrCoolzic zha-network-card  is using the LQI from the last received message from the device and also the time stamp from it and the value can being very up and down between transactions.

The LQI in ZigZag and the ZHA integrated card is using the value from one network scan (before done by ZH map) scanned by the routers in the network how its seeing their children and siblings (and parents if presented) and the value is the medal value from the 5 last reported to the router.

Still being thrilled of wath Samantha is delivering then she is finished cooking the code well (Still v1 user here) !!

**Comment by DrCoolzic** [comment]
Many thanks for the information. I am starting to better understand how things works with the help of @Adminiuga ( see reported problem here https://github.com/home-assistant/core/issues/44954#issuecomment-756990626 )

And yes the work of Samantha looks very promising. Many thanks to all of you for the great work you are doing. Unfortunately for me I am not familiar with the languages used in HA so I have hard time to understand all the pieces (I am a C, C++, C# programmer!).

**Comment by MattWestb** [comment]
Yes his is have great knowledge and also can explaining deep thing for advance and novice users that is not so common for one good technician.

And im one (nearly) no programmer and coming from the hardware side with telecommunication in the ground. But i finding Zigbee very interesting then its many man years knolage putting together from some of the worlds best companies in the branch and have great potentials if being used in the right way.

And one more good thing with ZHA is that they is using the community knowledge in the project in one very good way and also sharing it with other parts of the HA community (also with commercial ones like deCONZ).

**Comment by DrCoolzic** [comment]
Keep up the good work!
For information I am also trying to understand why the end devices connected to the ConBee are not reported correctly as neighbour ( see https://github.com/home-assistant/core/issues/44954)

**Comment by MattWestb** [comment]
Normally all platforms have good and bad sides and deCONZ have some very nice but also some not so good "personalities" but the most bad thing is its very proprietary and is maintained of only fue persons that have the knowledge to do that and dont spending so much times doing that.
Good its the radio performance but the back side its not easy getting end devices using routers then the coordinator is "stronger" = not always the best to connecting 2. That is sometimes making the network / mesh not working as expected and is getting problem then the coordinator is offline. Normally its better having end devices connected to routers that is 24/7 and not losing end devices then doing maintenance of the system.

**Comment by Samantha-uk** [comment]
> Thanks. Let me know if you want me to do more tests.
> May I ask quick questions? :
> 
> * For the graph construction are you using the information from the SQlite zigbee.db database?
> * Do you know why the information displayed with the zha-network-card have totally different LQI values?

If you are using `plugin-data-zha` *alll* the information is coming from ZHA
Zigzag issues a request to ZHA which returns a json (?) response and it all goes from that.

> Many thanks for the information. I am starting to better understand how things works with the help of @Adminiuga ( see reported problem here [home-assistant/core#44954 (comment)](https://github.com/home-assistant/core/issues/44954#issuecomment-756990626) )
> 
> And yes the work of Samantha looks very promising. Many thanks to all of you for the great work you are doing. Unfortunately for me I am not familiar with the languages used in HA so I have hard time to understand all the pieces (I am a C, C++, C# programmer!).

My background (pre ITU nursing) was pascal/c/c++/c# ... I'd never written more than perhaps 20 lines of javascript.  My recent forays into Typescript have been such fun ... I can highly recommend dipping your toe in the water :)

**Comment by Samantha-uk** [comment]
I believe that 8aa677512535b3167c83b88a81df7405adefa05f fixes this.
Can you try with the new version and let me know if it resolves your issue?

**Comment by DrCoolzic** [comment]
As soon as I will reinstall ZHA (probably in a couple of days) it will try it and let you know

**Comment by DrCoolzic** [comment]
I just restarted to use ZHA so currently only one node!
![image](https://user-images.githubusercontent.com/6078364/104814171-ad491880-580d-11eb-94c6-7e69a8c52e49.png)

Then I have stopped HA app and cleared the cache 

![image](https://user-images.githubusercontent.com/6078364/104814107-61966f00-580d-11eb-834b-1218f60dcd82.png)

So thanks it fixes the problem
