### ISSUE TITLE
[request] hacs

### ISSUE THREAD

**Issue by ViperRNMC** [Samantha-uk/one#8]
**Is your feature request related to a problem? Please describe.**
it's hard to install the zigzag plugin, hacs installation should be nice

**Describe the solution you'd like**
integration in hacs

**Comment by Samantha-uk** [comment]
Yes, I **totally** agree.
An early architectural choice I made was to use Yarn v2 and have my code in a monorepo.  This has brought some significant advantages and a few drawbacks; one of these is that HACS does not support installation from a monorepo.  (_I spoke with the chief maintainer of HACS to confirm this_)

So ... at some point in the near future, I will be copying the zigzag_panel code into a HACS compatible [repo](https://github.com/Samantha-uk/zigzag-panel) to make it easier for users to install.

**Comment by ViperRNMC** [comment]
nice, thanks for the hard work, like this map better then the one in core

**Comment by Samantha-uk** [comment]
OK.
Zigzag at _present_ could be installed via HACS, however ...
There are features on the roadmap that it appears **must** be added as an addon, which HACS does not support.
As such I'm working on migrating the feature-set to an addon which will support an easy install via the HA Supervisor; I'm afraid a HACS (in it's present form) install will not be supported.
